#!/bin/bash

#
# Universidad de Granada
# Departamento de Teoría de la Señal, Telemática y Comunicaciones.
#
# Archivo : detectorAtaque
#
# Autor :
#       Alejandra Cordero 
#  

# Se comprueba si el numero de flags introducidos es correcto.
if [ ${#@} -gt '2' ]
    then
        echo "Ha introducido mas flags de los debidos:";
        echo "./detectorAtaque (--evl | --trainingOffline | --trainingOnline) paquetesCapturados.pcap"; 
        exit 1;
    
elif [ ${#@} -lt '2' ]
    then
        echo "Ha introducido menos flags de los debidos:";
        echo "./detectorAtaque (--evl | --trainingOffline | --trainingOnline) paquetesCapturados.pcap"; 
        exit 1;
    fi

# read the options
TEMP=`getopt -o eti --long evl:,trainingOffline:,trainingInline: -- "$@"`
eval set -- "$TEMP"

# extract options and their arguments into variables.
while true ; do
    case "$1" in
        --evl)  bro -C -r $2 mainEvaluacion.bro; exit 1 ;;
        --trainingOffline) bro -C -r $2 mainEntrenamientoOffline.bro; exit 1 ;;
        --trainingOnline) bro -C -r $2 mainEntrenamientoOnline.bro; exit 1;;
        --) shift ; break ;;
        *) echo "./detectorAtaque (--evl | --trainingOffline | --trainingOnline) paquetesCapturados " ;
           exit 1 ;;
    esac
done
