#!/bin/bash

# Se comprueba si el numero de flags introducidos es correcto.
if [ ${#@} -gt '2' ]
    then
        echo "Ha introducido mas flags de los debidos."
        exit 1
    fi

# read the options
TEMP=`getopt -o eti --long evl:,trainingOffline:,trainingInline: -- "$@"`
eval set -- "$TEMP"

# extract options and their arguments into variables.
while true ; do
    case "$1" in
        -e|--evl)  bro -C -r $2 mainEvaluacion.bro; exit 1 ;;
        -t|--trainingOffline) bro -C -r $2 mainEntrenamiento.bro; exit 1 ;;
        -i|--trainingInline) bro -C -r $2 entrenamientoInline.bro; exit 1;;
        --) shift ; break ;;
        *) echo "Internal error!" ; exit 1 ;;
    esac
done